
GET http://localhost:8080/jobs

###

POST http://localhost:8080/jobs
Content-Type: application/json

{
  "title": "Desenvolvedor Full Stack",
  "role": "Desenvolvimento",
  "description": "Descrição do trabalho de desenvolvedor full stack",
  "requirements_qualifications": [
    "Experiência com JavaScript e frameworks front-end",
    "Experiência com linguagens de back-end como Node.js ou Python"
  ],
  "working_model": "remote",
  "process_steps": [
    "Análise de requisitos",
    "Desenvolvimento de funcionalidades",
    "Testes unitários e de integração"
  ],
  "company": "Empresa XPTO",
  "location": "São Paulo, SP",
  "salary": 8000,
  "link": "https://www.exemplo.com/vagas/123",
  "expiration_date": "2024-08-10T00:00:00Z",
  "additional_information": "Benefícios: vale transporte, plano de saúde."
}
